### PR TITLE
Block based 'on tap' code for when a user taps an alert

### PR DESCRIPTION
**Pull request by tonymillion**
Allows you to set a block to be executed when a user taps an alert.

you can do something like

```
    YRDropdownView * ydd = [YRDropdownView showDropdownInView:self.window 
                                       title:NSLocalizedString(@"Awwww :(", @"")];

                        ydd.tapBlock = ^{ NSLog(@"Alert Tapped!") };
```

### CODE REVIEW

**Comment by eliperkins** [comment]
Nice! This is an awesome addition. The only thing I'm unsure about is the need for executing the block on the main thread. Is there a reason that you chose to execute it on the main thread? I'm thinking it might be better to let the user decide what thread it should be on.

**Comment by tonymillion** [comment]
I agree, and had that initially, but changed it for the submission as I figured most of the time a tap would lead to UI work, which would require a main thread dispatch anyway.

I'm happy to add it all back and submit another pull request

**Comment by tonymillion** [comment]
This should do it… User assignable block and compiled cleanly on ARC too

**Comment by eliperkins** [comment]
Awesome! Thanks for hashing this one out, Tony.

**Pull request merged**
